// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaliCanon.Data.Sql;

namespace PaliCanon.Data.Sql.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.AuthorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("author");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Nikaya")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("book");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.ChapterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Citation")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookId");

                    b.ToTable("chapter");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.VerseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("int");

                    b.Property<int?>("VerseNumberLast")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("verse");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.ChapterEntity", b =>
                {
                    b.HasOne("PaliCanon.Data.Sql.Entities.AuthorEntity", "Author")
                        .WithMany("Chapters")
                        .HasForeignKey("AuthorId");

                    b.HasOne("PaliCanon.Data.Sql.Entities.BookEntity", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.VerseEntity", b =>
                {
                    b.HasOne("PaliCanon.Data.Sql.Entities.ChapterEntity", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.AuthorEntity", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.BookEntity", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("PaliCanon.Data.Sql.Entities.ChapterEntity", b =>
                {
                    b.Navigation("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
