version: '3.2'

services:
  db:
    image: timbrownls26/palicanondb:1.0
    container_name: db
    build:
      context: .
      dockerfile: PaliCanon.Api\DockerfileDb
    ports:
      - "49301:3306"
    environment:
      MYSQL_USER: palicanon
      MYSQL_PASSWORD: B0dh1Tr33
      MYSQL_DATABASE: palicanon
      MYSQL_ROOT_PASSWORD: B0dh1Tr33
  app:
    image: timbrownls26/palicanon:1.0
    container_name: app
    build:
      context: .
      dockerfile: PaliCanon.Api\Dockerfile
    ports:
      - "49501:80"
    environment:
      - "ConnectionStrings:MySql=Server=db;Port=3306;Database=palicanon;Uid=palicanon;Pwd=B0dh1Tr33;SslMode=None;ConnectionReset=false;connect timeout=3600"     

